name: integracion continua con node.js

on:
  pull_request:
    branches: [master]

jobs:
  ci_to_master:
    run-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
